CREATE TABLE STUDENT (
    rollno int,
    name varchar(20),
    marks int,
    address varchar(100),
    age int
);
INSERT INTO STUDENT VALUES(1, 'Arhan', 90, 'Delhi', 20);
INSERT INTO STUDENT VALUES(2, 'Hardik', 80, 'Delhi', 21);
INSERT INTO STUDENT VALUES(3, 'Raj', 70, 'Delhi', 22);
INSERT INTO STUDENT VALUES(4, 'Rajesh', 60, 'Delhi', 23);
INSERT INTO STUDENT VALUES(5, 'Rajesh', 50, 'Delhi', 24);
CREATE TABLE STUDENTCOURSE (
    courseID int, 
    rollno int
);
INSERT INTO STUDENTCOURSE VALUES(1, 1);
INSERT INTO STUDENTCOURSE VALUES(1, 4);
INSERT INTO STUDENTCOURSE VALUES(2, 5);
INSERT INTO STUDENTCOURSE VALUES(2, 7);
INSERT INTO STUDENTCOURSE VALUES(3, 8);



-- DROP TABLE STUDENT;
-- DROP TABLE STUDENTCOURSE;

dbms_output.put_line('INNER JOIN');
SELECT * from STUDENT INNER JOIN STUDENTCOURSE on STUDENT.rollno = STUDENTCOURSE.rollno;
dbms_output.put_line('LEFT JOIN');
SELECT * from STUDENT LEFT JOIN STUDENTCOURSE on STUDENT.rollno = STUDENTCOURSE.rollno;
dbms_output.put_line('RIGHT JOIN');
SELECT * from STUDENT RIGHT JOIN STUDENTCOURSE on STUDENT.rollno = STUDENTCOURSE.rollno;
dbms_output.put_line('FULL JOIN');
SELECT * from STUDENT FULL JOIN STUDENTCOURSE on STUDENT.rollno = STUDENTCOURSE.rollno;